version: '3.4'
services:
    postgres_1:
        image: postgres:13
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
          - postgres-data:/var/lib/postgresql/data
        ports:
          - 5439:5432
        networks:
          - bridge

    webserver_1:
        image: puckel/docker-airflow:1.10.9
        ports:
          - "8080:8080"
        environment:
          - LOAD_EXAMPLES=no
          - EXECUTOR=Local
          - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
        volumes:
          - ./dags:/usr/local/airflow/dags
          - ./logs:/usr/local/airflow/logs
          - ./plugins:/usr/local/airflow/plugins
        command: webserver
        depends_on:
          - postgres_1
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        links:
          - postgres_1
        networks:
          - bridge
        
        

volumes:
  postgres-data:
networks:
  bridge: